# Generated by Django 3.2 on 2025-02-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_duty',
            field=models.BooleanField(default=False, verbose_name='Дежурный врач'),
        ),
    ]
